# Eigenvalues and Eigenvectors

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook


$$\vec{A} = 
\begin{pmatrix}
 11 &  -1 & 0\\
-1 &  12 & -1\\
 0 &  -1 & 11
\end{pmatrix}
$$

Find the eigenvalues and eigenvectors for the equation:

$$(\vec{A} - \lambda\vec{I})\vec{v} = 0,$$
where $\vec{v}$ are the eigenvectors and $\lambda$ is the eigenvalues

In [2]:
#define matrix
A = np.array([[11,-1,0],[-1,12,-1],[0,-11,1]])
print(A)

[[ 11  -1   0]
 [ -1  12  -1]
 [  0 -11   1]]


In [3]:
#find eigenvaules and eigenvectors
w,v = np.linalg.eig(A)
print('E-value:', w)
print('E-vector', v)

E-value: [13.32309351 10.60613838  0.07076812]
E-vector [[ 0.30575364  0.85795412  0.00770167]
 [-0.71029429  0.3379152   0.08417332]
 [ 0.63403213 -0.38694708  0.99642137]]
